# Generated by Django 4.1 on 2022-08-10 19:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0005_animal_user'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Toy',
            new_name='Fruit',
        ),
        migrations.RenameField(
            model_name='animal',
            old_name='toys',
            new_name='fruits',
        ),
    ]
